"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FLAG = exports.REG_NAMES = exports.REG = exports.CPU = exports.Memory = void 0;
var Memory_ts_1 = require("./Memory.ts");
Object.defineProperty(exports, "Memory", { enumerable: true, get: function () { return Memory_ts_1.Memory; } });
var CPU_ts_1 = require("./CPU.ts");
Object.defineProperty(exports, "CPU", { enumerable: true, get: function () { return CPU_ts_1.CPU; } });
Object.defineProperty(exports, "REG", { enumerable: true, get: function () { return CPU_ts_1.REG; } });
Object.defineProperty(exports, "REG_NAMES", { enumerable: true, get: function () { return CPU_ts_1.REG_NAMES; } });
Object.defineProperty(exports, "FLAG", { enumerable: true, get: function () { return CPU_ts_1.FLAG; } });
